# Generated by Django 3.2.6 on 2021-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_auto_20210821_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp436', max_length=70),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.CharField(max_length=40),
        ),
    ]
